#!/bin/sh

docroot='.'
test -n "$1" && docroot="$1"
test -f "$docroot/conf" && . "$docroot/conf"

find "$docroot" -name '*.css' -o -name '*.html' -o -name '*.js' \
     -o -name '*.txt' \
| {
   while IFS= read -r file; do
     if [ "$line" -nt "$file.gz" -o ! -f "$file.gz" ] ; then
       gzip -9 < "$file" > "$file.gz";
     fi
   done
 }
